resource_group_name         = "my_terraform_rg"
resource_group_location     = "central india"
virtual_network_name        = "vnettest019"
subnet_name                 = "subnet019"
public_ip_name              = "publicip019"
network_security_group_name = "nsgtest019"
network_interface_name      = "nictest019"
linux_virtual_machine_name  = "linuxvm019"
